# Generated by Django 5.1.4 on 2025-12-27 17:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('ai', 'AI'), ('local', 'Local'), ('online', 'Online')], max_length=10)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('finished', 'Finished'), ('aborted', 'Aborted')], default='waiting', max_length=10)),
                ('rated', models.BooleanField(default=False)),
                ('current_turn', models.CharField(default='X', max_length=1)),
                ('next_board_constraint', models.IntegerField(blank=True, help_text='Cache: Which sub-board must be played? NULL = any', null=True)),
                ('move_count', models.IntegerField(default=0)),
                ('last_move_at', models.DateTimeField(blank=True, null=True)),
                ('winner', models.CharField(blank=True, help_text='Cache: X, O or D', max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('player_o', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_o', to=settings.AUTH_USER_MODEL)),
                ('player_x', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_x', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_no', models.IntegerField()),
                ('player', models.CharField(max_length=1)),
                ('cell', models.IntegerField(help_text='0-8')),
                ('subcell', models.IntegerField(help_text='0-8')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='games.game')),
            ],
            options={
                'ordering': ['move_no'],
                'unique_together': {('game', 'move_no')},
            },
        ),
    ]
