# Generated by Django 5.2.7 on 2026-01-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='mode',
            field=models.CharField(choices=[('ai', 'AI'), ('local', 'Local'), ('custom', 'Custom')], max_length=10),
        ),
    ]
