# Generated by Django 5.1.4 on 2026-01-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_gameinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_o_xp_gained',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='player_x_xp_gained',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
