# Generated by Django 5.2.7 on 2026-01-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_player_o_xp_gained_game_player_x_xp_gained'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='mode',
            field=models.CharField(choices=[('ai', 'AI'), ('local', 'Local'), ('custom', 'Custom'), ('unranked', 'Unranked')], max_length=10),
        ),
    ]
