# Generated by Django 5.2.7 on 2026-01-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_o_mmr_change',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='player_x_mmr_change',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
