# Generated by Django 5.2.7 on 2026-01-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_player_o_mmr_change_game_player_x_mmr_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='mode',
            field=models.CharField(choices=[('ai', 'AI'), ('local', 'Local'), ('custom', 'Custom'), ('unranked', 'Unranked'), ('ranked', 'Ranked')], max_length=10),
        ),
    ]
