# Generated by Django 5.2.7 on 2026-01-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_game_player_o_lp_change_game_player_x_lp_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='mode',
            field=models.CharField(choices=[('ai', 'AI'), ('bot_easy', 'Bot Easy'), ('local', 'Local'), ('custom', 'Custom'), ('unranked', 'Unranked'), ('ranked', 'Ranked')], max_length=10),
        ),
    ]
