# Generated by Django 5.2.7 on 2026-02-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_alter_game_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='mode',
            field=models.CharField(choices=[('ai', 'AI'), ('bot_easy', 'Bot Easy'), ('bot_medium', 'Bot Medium'), ('bot_hard', 'Bot Hard'), ('local', 'Local'), ('custom', 'Custom'), ('unranked', 'Unranked'), ('ranked', 'Ranked')], max_length=10),
        ),
    ]
