# Generated by Django 5.2.7 on 2026-02-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_alter_game_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bot_difficulty',
            field=models.IntegerField(default=0, help_text='0-100, probability of random move (for custom bot)'),
        ),
    ]
