# Generated by Django 5.2.7 on 2026-02-01 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
