# Generated by Django 5.2.7 on 2026-02-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('chat', 'Chat'), ('evaluation', 'Evaluation')], default='chat', max_length=20),
        ),
    ]
