# Generated by Django 5.2.7 on 2026-02-16 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_chatmessage_message_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='current_turn',
        ),
        migrations.RemoveField(
            model_name='game',
            name='last_move_at',
        ),
        migrations.RemoveField(
            model_name='game',
            name='move_count',
        ),
        migrations.RemoveField(
            model_name='game',
            name='next_board_constraint',
        ),
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
    ]
