# Generated by Django 5.2.7 on 2026-02-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_remove_game_current_turn_remove_game_last_move_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.CharField(blank=True, help_text='X, O, or D', max_length=1, null=True),
        ),
    ]
