# Generated by Django 5.2.7 on 2026-01-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_country_playerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='mmr',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='placement_games_played',
            field=models.IntegerField(default=0),
        ),
    ]
