# Generated by Django 5.2.7 on 2026-01-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_playerprofile_mmr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='total_lp',
            field=models.IntegerField(default=0),
        ),
    ]
