# Generated by Django 5.2.7 on 2026-01-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_playerprofile_total_lp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='mmr',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='total_lp',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
