# Generated by Django 5.2.7 on 2026-01-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_playerprofile_mmr_alter_playerprofile_total_lp'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
    ]
