# Generated by Django 5.2.7 on 2026-02-01 16:20
# Force reload

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_playerprofile_current_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='avatar_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
