# Generated by Django 5.2.7 on 2026-02-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='demotion_shield',
            field=models.IntegerField(default=0),
        ),
    ]
