# Generated by Django 5.2.7 on 2026-02-16 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_playerprofile_demotion_shield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='current_xp',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='level',
        ),
    ]
