# Generated by Django 5.2.7 on 2026-02-16 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_playerprofile_current_xp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='avatar_config',
        ),
        migrations.CreateModel(
            name='AvatarConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_type', models.CharField(max_length=100)),
                ('accessories_type', models.CharField(max_length=100)),
                ('hair_color', models.CharField(max_length=100)),
                ('facial_hair_type', models.CharField(max_length=100)),
                ('clothe_type', models.CharField(max_length=100)),
                ('eye_type', models.CharField(max_length=100)),
                ('eyebrow_type', models.CharField(max_length=100)),
                ('mouth_type', models.CharField(max_length=100)),
                ('skin_color', models.CharField(max_length=100)),
                ('player_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_config', to='users.playerprofile')),
            ],
        ),
    ]
